[package]
name = "crypta"
version = "0.1.0"
authors = ["Lance Hart<me@lancehart.ca>"]
edition = "2021"
description = "Cryptography Library"
repository = "https://github.com/shipsimfan/crypta"
license = "GPL-3.0-or-later"
publish = false
